[package]
name = "yottafs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "bench",
    "client",
    "e2e",
    "drivers/*",
    "packages/*",
    "services/*",
]

[dependencies]
config = { path = "./packages/config" }
clap = { version = "4.0.32", features = ["derive"] }
